image: node:16

variables:
  NPM_TOKEN: $NPM_TOKEN

stages:
  - build
  - publish

build:
  stage: build
  artifacts:
    paths:
      - dist
  cache:
    key: $CI_COMMIT_REF_NAME
    policy: push
    paths:
      - node_modules
  script:
    - yarn
    - yarn build

publish:
  stage: publish
  script:
    - npm install -g npm@latest
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - npm version --no-git-tag-version $CI_COMMIT_TAG --allow-same-version
    - npm publish
  only:
    - tags

pages:
  stage: publish
  script:
    - npm install -g npm@latest
    - mv dist/docs public
  artifacts:
    paths:
      - public
  only:
    - tags