image: node:16

variables:
  NPM_TOKEN: $NPM_TOKEN

stages:
  - build
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - dist
  cache:
    key: $CI_COMMIT_REF_NAME
    policy: push
    paths:
      - node_modules
  script:
    - yarn
    - yarn build

publish:
  stage: deploy
  script:
    - npm install -g npm@latest
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - npm version --no-git-tag-version $CI_COMMIT_TAG --allow-same-version
    - npm_publish() { npm publish 2>&1; echo "$?" >> /tmp/npm_status.txt; }; npm_publish | tee /tmp/npm.txt
    - if [[ ! "$(cat /tmp/npm_status.txt)" -eq "0" ]] && [[ -z "$(cat /tmp/npm.txt | grep "You cannot publish over the previously published versions:")" ]]; then exit 1; fi;
  only:
    - main
  allow_failure: true

pages:
  stage: deploy
  script:
    - npm install -g npm@latest
    - mv dist/docs public
  artifacts:
    paths:
      - public
  only:
    - main